# Mathematics

In [2]:
import numpy as np

In [3]:
a = np.array([1,5,7,9])
print(a)

[1 5 7 9]


In [4]:
a+2

array([ 3,  7,  9, 11])

In [5]:
a-7

array([-6, -2,  0,  2])

In [6]:
a*4

array([ 4, 20, 28, 36])

In [7]:
a/2

array([0.5, 2.5, 3.5, 4.5])

In [8]:
b = np.array([3,4,8,2])
a + b

array([ 4,  9, 15, 11])

In [9]:
a ** 2

array([ 1, 25, 49, 81])

### Trigo function

In [10]:
np.sin(b)

array([ 0.14112001, -0.7568025 ,  0.98935825,  0.90929743])

In [11]:
np.tan(b)

array([-0.14254654,  1.15782128, -6.79971146, -2.18503986])

### Linear Algebra


In [18]:
c = np.ones((2,3))
d = np.full((3,4) , 3)
e = np.random.randint(3, 10 , size=(3,3))
np.matmul(c,d)


array([[9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [19]:
np.linalg.det(e)

-32.000000000000014

In [23]:
# np.linalg.eigvals(3)
e.ndim

2

[NumPy Documentation For Math Functions](https://numpy.org/doc/stable/reference/generated/numpy.sum.html)



[NumPy Documentation For Linear Alzebra](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eigvals.html)


### Statistics

In [24]:
stats = np.array([[1,2,4] , [6,7,9]])
stats

array([[1, 2, 4],
       [6, 7, 9]])

In [26]:
np.min(stats)

1

In [27]:
np.max(stats)

9

In [28]:
np.sum(stats)

29

In [30]:
np.exp(stats)

array([[2.71828183e+00, 7.38905610e+00, 5.45981500e+01],
       [4.03428793e+02, 1.09663316e+03, 8.10308393e+03]])