# Accessing / Changing specific elements , rows , columns , etc

In [2]:
import numpy as np

In [3]:
a = np.array([[2,3,4,5,6,7] , [8,6,5,3,12,5]])
print(a)

[[ 2  3  4  5  6  7]
 [ 8  6  5  3 12  5]]


### Get a specific elememt *[rows , column]* 

In [10]:
a[1 , -1]

5

In [12]:
a[1 , 4]

12

### Get a specific row *[row , : ]* 

In [8]:
a[1 , :]

array([ 8,  6,  5,  3, 12,  5])

### Get a specific column *[ : , column]* 

In [7]:
a[ : , 4]

array([ 6, 12])

### Getting a little more fancy *[startindex , endindex , stepsize]*

In [17]:
a[0 , 1 : -1 : 2]

array([3, 5])

In [16]:
a[0 , 1 :  : 2]

array([3, 5, 7])

In [18]:
a[0 , 1 : 4 : 1]

array([3, 4, 5])

### changing an element , rows and column

In [21]:
a[1,4] = 20

In [22]:
a[: , 1] = [11 , 22]

In [23]:
print(a)

[[ 2 11  4  5  6  7]
 [ 8 22  5  3 20  5]]


### working with 3d array

In [30]:
b = np.array([[[1,2,3] , [4,5,6]] , [[6,7,8] , [9,10,11]]])
print(b)
print(b.shape)
print(b.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
3


In [45]:
b[0 , 1 , 2]

6

# Initializing different types of arrays

### Null matrix

In [49]:
null = np.zeros((4,6))
print(null)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


### all 1 matrix

In [43]:
np.ones((2,3 ,4) , dtype="int8")

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

### any other matrix

In [48]:
np.full((2,3,4) , 99)

array([[[99, 99, 99, 99],
        [99, 99, 99, 99],
        [99, 99, 99, 99]],

       [[99, 99, 99, 99],
        [99, 99, 99, 99],
        [99, 99, 99, 99]]])

In [50]:
np.full_like(null , 49)

array([[49., 49., 49., 49., 49., 49.],
       [49., 49., 49., 49., 49., 49.],
       [49., 49., 49., 49., 49., 49.],
       [49., 49., 49., 49., 49., 49.]])

### Random decimal number


In [51]:
np.random.rand(4,2)

array([[0.07434872, 0.22568665],
       [0.1045646 , 0.05761845],
       [0.71367666, 0.78334692],
       [0.53795594, 0.09834291]])

In [52]:
np.random.random_sample(null.shape)

array([[0.12404427, 0.36589558, 0.11920248, 0.90859777, 0.42777568,
        0.16687821],
       [0.393441  , 0.91149308, 0.59541209, 0.51500203, 0.08121689,
        0.30908391],
       [0.13485748, 0.60134764, 0.45202358, 0.91111822, 0.5026017 ,
        0.92444322],
       [0.12872948, 0.21059863, 0.9586407 , 0.53939228, 0.5665583 ,
        0.0848676 ]])

### Random integer number


In [58]:
np.random.randint(3 , 8 , size=(3,3))

array([[5, 5, 3],
       [3, 4, 7],
       [7, 4, 3]])

### The identity matrix


In [59]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Repeat an array

In [64]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr , 3 , axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


### Exercise

In [65]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [66]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [68]:
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [69]:
output[1:-1 , 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Carefull while copying 

In [72]:
a = np.array([12,43,15])
b = a
b[2] = 20
print(b[2])
print(a[2])

20
20


In [73]:
c = a.copy()
c[2] = 99
print(c[2])
print(a[2])

99
20
