# Numpy


## This is a NumPy Tutorial


**The Basics**
You can create NumPy arrays using `np.array()` function.


In [3]:
import numpy as np

*1D-Array*

In [42]:
a = np.array([1,2,4] , dtype = "int8")
print(a)

[1 2 4]


*2D-Array*

In [54]:
b = np.array([[2 , 4.0 , 4] , [5 ,7.1 , 2]])
print(b)
print("\n")
c = np.array([[1,2,4] , [5,6,7] , [7,8,9]] , dtype = "int32")
print(c)

[[2.  4.  4. ]
 [5.  7.1 2. ]]


[[1 2 4]
 [5 6 7]
 [7 8 9]]


*3D-Array*

In [33]:
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],
                   
                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]] , dtype="int64")

print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


*Get Dimention*

In [19]:
arr_3d.ndim

3

*Get Shape*

In [25]:
print(a.shape)
print(b.shape)
print(c.shape)
print(arr_3d.shape)

(3,)
(2, 3)
(3, 3)
(3, 3, 3)


*Get Type*

In [47]:
arr_3d.dtype

dtype('int64')

*Get Size (in bytes)*

In [43]:
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)
print(arr_3d.itemsize)

1
2
4
8


*Get Total Number of Elements*

In [49]:
print(a.size)
print(b.size)
print(arr_3d.size)

3
6
27


*Get Total Size (in bytes)*

In [52]:
print(c.size * c.itemsize)
print(arr_3d.size * arr_3d.itemsize)
print(arr_3d.nbytes)

36
216
216


In [55]:
b.nbytes

48